# Generated by Django 4.2.6 on 2023-10-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The full name of the Team member.', max_length=255)),
                ('email', models.EmailField(help_text='The email address of the Team member.', max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(help_text='The age of the Team member.')),
                ('phone', models.CharField(help_text='The phone number of the Team member.', max_length=20)),
                ('access', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('manager', 'Manager')], default='user', help_text="The level of access granted to the user (e.g., 'admin', 'manager', 'user').", max_length=20)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
