# Generated by Django 4.2.6 on 2023-10-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(help_text='The unique identifier for the customer contact.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The full name of the customer contact.', max_length=255)),
                ('email', models.EmailField(help_text='The email address of the customer contact.', max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(help_text='The age of the customer contact.')),
                ('phone', models.CharField(help_text='The phone number of the customer contact.', max_length=20)),
                ('access', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('manager', 'Manager')], default='user', help_text="The level of access granted to the customer contact (e.g., 'admin', 'manager', 'user').", max_length=20)),
            ],
            options={
                'verbose_name': 'Customer Contact',
                'verbose_name_plural': 'Customer Contacts',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(help_text='The unique identifier for the invoice.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The full name associated with the invoice.', max_length=255)),
                ('email', models.EmailField(help_text='The email address associated with the invoice.', max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, help_text='The cost of the invoice.', max_digits=8)),
                ('phone', models.CharField(help_text='The phone number associated with the invoice.', max_length=20)),
                ('date', models.DateField(help_text='The date of the invoice.')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
