# Generated by Django 4.2.6 on 2023-10-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customercontact_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='The country of the data.', max_length=255)),
                ('Hotdog', models.IntegerField(help_text='The number of hot dogs sold.')),
                ('HotdogColor', models.CharField(help_text='The color of the hot dog bar.', max_length=255)),
                ('Burger', models.IntegerField(help_text='The number of burgers sold.')),
                ('BurgerColor', models.CharField(help_text='The color of the burger bar.', max_length=255)),
                ('Kebab', models.IntegerField(help_text='The number of kebabs sold.')),
                ('KebabColor', models.CharField(help_text='The color of the kebab bar.', max_length=255)),
                ('donut', models.IntegerField(help_text='The number of donuts sold.')),
                ('donutColor', models.CharField(help_text='The color of the donut bar.', max_length=255)),
            ],
            options={
                'verbose_name': 'BarData',
                'verbose_name_plural': 'BarDatas',
            },
        ),
        migrations.CreateModel(
            name='LineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDline', models.CharField(help_text='The ID associated with the linechart.', max_length=255)),
                ('color', models.CharField(help_text='The colour associated with the linechart.', max_length=255)),
                ('data', models.JSONField(help_text='The data associated with the linechart.')),
            ],
            options={
                'verbose_name': 'LineData',
                'verbose_name_plural': 'LineDatas',
            },
        ),
        migrations.CreateModel(
            name='PieData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDpie', models.CharField(help_text='The ID associated with the piechart.', max_length=255)),
                ('label', models.CharField(help_text='The label associated with the piechart.', max_length=255)),
                ('value', models.IntegerField(help_text='The value associated with the piechart.')),
                ('colour', models.CharField(help_text='The colour associated with the piechart.', max_length=255)),
            ],
            options={
                'verbose_name': 'PieData',
                'verbose_name_plural': 'PieDatas',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txId', models.CharField(help_text='The ID associated with the invoice.', max_length=255)),
                ('user', models.CharField(help_text='The email address associated with the invoice.', max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, help_text='The cost of the product.', max_digits=8)),
                ('date', models.DateField(help_text='The date of the invoice.')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='access',
        ),
        migrations.AddField(
            model_name='customercontact',
            name='address',
            field=models.CharField(blank=True, help_text='The address of the customer.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='city',
            field=models.CharField(blank=True, help_text='The city of the customer.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='registrarId',
            field=models.CharField(blank=True, help_text='The registrarId of the customer.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='zipCode',
            field=models.CharField(blank=True, help_text='The zipCode of the customer.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
